spring.application.name=demo

# # {POSTGRES SUPERBASE}
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.abtxwdfzsfjnmxpwgcou
spring.datasource.password=amd2817elitebook
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# {GENERAL USE SQL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:10000}
# spring.datasource.hikari.data-source-properties.ssl=true
# spring.datasource.hikari.data-source-properties.sslmode=require
# spring.datasource.hikari.maximum-pool-size=5


# {MYSQL}
# spring.datasource.url=jdbc:mysql://localhost:3306/tfdemo
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.datasource.username=root
# spring.datasource.password=

